services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag x11vnc/wine:2.6 --tag x11vnc/wine:latest . && docker push x11vnc/wine
  - docker images
